### ISSUE TITLE
more example

### ISSUE THREAD

**Issue by programmer-liu** [vapourismo/knx-go#50] opened 2022-06-20 08:37 UTC
i try  connect to knx virtual in another machine, code below
` client, err := knx.NewGroupTunnel("224.0.23.12:3671", knx.DefaultTunnelConfig)

	if err != nil {
		log.Errorf(err)
	}

	defer client.Close()

	for msg := range client.Inbound() {
		fmt.Println(msg.Data)
	}`
when my long press button,knx virtual display light is on,but code not print anything,what's matter?

**Comment by programmer-liu** [comment] 2022-06-20 08:59
still fail,or have some setting in knx virtual or ETS?
ETS and knx virtual runing on windows, code runing on linux
![1](https://user-images.githubusercontent.com/25048144/174565293-00014400-a151-4168-8a94-54d2c65a3b6d.png)

![2](https://user-images.githubusercontent.com/25048144/174565315-bfde6298-75a9-4a8f-80a6-137534d79b03.png)

**Comment by vapourismo** [comment] 2022-06-20 10:29
Ok, that sounds a lot like there is a network issue with your setup. Not related to this package.

First clarify whether the thing you're trying to connect to is a gateway (use GroupTunnel) or a router (use GroupRouter). 

Then make sure the machine you're running this on can actually connect. For instance, when you're running the KNX virtual on localhost (127.0.0.1) then the problem is that your VM will not be able to access that given they don't share the loopback network interface.

I am closing this for now because the issue is with your network setup not 'knx-go'.

**Closed** 2022-06-20 10:30 UTC
